dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3308/sharding_db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3308/sharding_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  read_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3309/sharding_db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  read_ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3309/sharding_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
rules:
  # 读写分离
  - !READWRITE_SPLITTING
    dataSourceGroups:
      readwrite_ds_0:
        writeDataSourceName: ds0
        readDataSourceNames:
          - read_ds_0
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: random
      readwrite_ds_1:
        writeDataSourceName: ds1
        readDataSourceNames:
          - read_ds_1
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: random
    loadBalancers:
      random:
        type: RANDOM
  # 广播表
  - !BROADCAST
    tables:
      - t_config
  - !SHARDING
    tables:
      # 取模分片，库取模，表取模
      t_user:
        actualDataNodes: ds${0..1}.t_user_${0..1}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: user_inline
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: db_inline
      # 按月分片 库取模，表按月
      t_user_log:
        actualDataNodes: ds${0..1}.user_log_${202401..202509}
        tableStrategy:
          standard:
            # 2024-01-12 08:45:00
            shardingColumn: create_time
            shardingAlgorithmName: month_inline
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: db_inline
      # 复合分片
      t_user_role:
        # 根据用户id和角色编码来进行复合分片
        actualDataNodes: ds0.t_user_role_${0..1}_${1..4}
        tableStrategy:
          complex:
            shardingColumns: user_id,role_code
            shardingAlgorithmName: user_role_complex
    shardingAlgorithms:
      # 取模分片
      db_inline:
        type: INLINE
        props:
          algorithm-expression: ds${id % 2}
      user_inline:
        type: INLINE
        props:
          algorithm-expression: t_user_${id % 2}
      # 按月分片，自定义分片
      month_inline:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.example.shardingjdbc.algorithm.MonthTableShardingAlgorithm
      # 复合分片
      user_role_complex:
        type: CLASS_BASED
        props:
          strategy: COMPLEX
          algorithmClassName: com.example.shardingjdbc.algorithm.UserRoleComplexShardingAlgorithm
      # 广播表

      # 读写分离

      # 分布式事务
# 分布式事务
transaction:
  defaultType: LOCAL

props:
  sql-show: true
