dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding_db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
rules:
  - !SHARDING
    tables:
      #      取模分片
      t_user:
        actualDataNodes: ds${0..1}.t_user_${0..1}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: user_inline
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: db_inline
      # 按月分片
      t_user_log:
        actualDataNodes: ds${0..1}.user_log_${202401..202509}
        tableStrategy:
          standard:
            # 2024-01-12 08:45:00
            shardingColumn: create_time
            shardingAlgorithmName: month_inline
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: db_inline
      # 复合分片
      # 广播表
      # 读写分离
      # 分布式事务
    shardingAlgorithms:
      # 取模分片
      db_inline:
        type: INLINE
        props:
          algorithm-expression: ds${id % 2}
      user_inline:
        type: INLINE
        props:
          algorithm-expression: t_user_${id % 2}
      # 按月分片，自定义分片
      month_inline:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.example.shardingjdbc.algorithm.MonthTableShardingAlgorithm

props:
  sql-show: true
