version: '3.8'
services:
  master:
    image: mysql:8.0.43
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./master/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./master/data:/var/lib/mysql

  slave:
    image: mysql:8.0.43
    container_name: mysql-slave
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - ./slave/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./slave/data:/var/lib/mysql
    depends_on:
      - master
